// React/src/App.tsx
import React from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import HtmlEditor, { HtmlEditorTypes, Item, Toolbar } from 'devextreme-react/html-editor';
import { markup } from './Markup';

function onInitialized(e: HtmlEditorTypes.InitializedEvent): void {
  const Uploader = e.component?.get('modules/uploader');
  class DisabledUploader extends Uploader {
    constructor(quill: any, options: any) {
      // eslint-disable-next-line spellcheck/spell-checker
      super(quill, { ...options, mimetypes: [] });
      // empty array to prevent any image type from being pasted
    }
  }
  e.component?.register({ 'modules/uploader': DisabledUploader });
}

function App(): JSX.Element {
  return (
    <div className="main">
      <p>Try dropping or pasting an image to the editor.</p>
      <HtmlEditor onInitialized={onInitialized} height={500} value={markup}>
        <Toolbar>
          <Item name="undo" />
          <Item name="redo" />
          <Item name="separator" />
          <Item name="clear" />
        </Toolbar>
      </HtmlEditor>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { DxHtmlEditorTypes } from 'devextreme-angular/ui/html-editor';
import { Service } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [Service],
})
export class AppComponent {
  valueContent: string;

  constructor(service: Service) {
    this.valueContent = service.getMarkup();
  }

  onInitialized(e: DxHtmlEditorTypes.InitializedEvent): void {
    const Uploader = e.component?.get('modules/uploader');
    class DisabledUploader extends Uploader {
      constructor(quill: any, options: any) {
        // eslint-disable-next-line spellcheck/spell-checker
        super(quill, { ...options, mimetypes: [] });
        // empty array to prevent any image type from being pasted
      }
    }
    e.component?.register({ 'modules/uploader': DisabledUploader });
  }
}

<p>Try dropping or pasting an image to the editor.</p>
<dx-html-editor (onInitialized)="onInitialized($event)" height="500px" [value]="valueContent">
  <dxo-toolbar>
    <dxi-item name="undo"></dxi-item>
    <dxi-item name="redo"></dxi-item>
    <dxi-item name="separator"></dxi-item>
    <dxi-item name="clear"></dxi-item>
  </dxo-toolbar>
</dx-html-editor>
